name: pipeline-bootcamp-m15
on:
  push:
    branches:
      - main

env:
  DockerHub_UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  DockerHub_Password: ${{ secrets.DOCKERHUB_TOKEN }}
  DockerHub_RepoName: spm-openjdk-bootcamp-m14
  DockerHub_TagName: github
  Docker_ContainerName: $DockerHub_RepoName
  Application_Original_Port: 3456
  Application_Expose_Port: 8001

jobs:
  bootcamp-m15-job:
    runs-on: ubuntu-latest
    steps:

      - name: contruir imagen docker a partir de dockerfile
        run:
          docker build -t ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_${{ github.run_id }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DockerHub_UserName}}
          password: ${{env.DockerHub_Password}}
